version: '3.9'

services:
  kali-webtop:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-webtop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Belem
    ports:
      - "3001:3001"
      - "3000:3000"
    volumes:
      - ./data/config:/config
    shm_size: "2gb"
    restart: unless-stopped
